name = "Blog"
license = "MIT"
licenselink = ""
description = "Theme for my blog."
homepage = "https://dotslashdash.github.io/hugo"
min_version = "0.41.0"

[author]
  name = "dotslashdash"
  homepage = "https://dotslashdash.github.io/hugo"
